### PR TITLE
Fix memory leak when creating and destroying a lot of context

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

During introducing https://github.com/netty/netty-tcnative/pull/759 I missed to add a free call which did introduce a small memory leak. This was not noticable for most users as creating and destroying of SSL context is usually very rare. That said some users might still do this and so notice the leak.

Modifications:

- Add missing free(...) call to match calloc(...)
- Move code of one function to the other as it was the only calling function. This simplifies the code and makes it less error-prone

Result:

Fixes https://github.com/netty/netty-tcnative/issues/788

### CODE REVIEW

**Review by franz1981 — APPROVED** [review]
@normanmaurer you can give a shot to the async profiler native memory leak branch!

**Comment by notdryft** [comment]
We're currently testing it against the async profiler nativemem mode ourselves!

**Comment by normanmaurer** [comment]
I could reproduce a leak anymore with this pulled in. Once you confirm it as well I will do a release

**Comment by franz1981** [comment]
Great @notdryft let me know if that worked too!

**Pull request merged**
