### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by davidben**
Note: I wasn't able to get netty working against the master branch with or without these changes, so you may wish to test that. I was able to build netty-tcnative standalone, so that much seems to work.

This cleans up a ton of dead code from netty-tcnative.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@davidben what master branch you are talking about ?

**Comment by davidben** [comment]
Er, the one this PR is targetting?
https://github.com/netty/netty-tcnative/tree/master

I don't understand your branching scheme, but this is the branch with the dead code removal, so it seemed natural to add further cleanup to it.

**Comment by Scottmitch** [comment]
@davidben - Awesome thanks!

In terms of not getting Netty working ... do our wikis need updating, or was it bcz we haven't released a Netty to use the new namespace `io.netty.tcnative`?

**Comment by davidben** [comment]
Oh, that might have been it? I'm not sure. I was using the 4.1 branch of netty because it seemed to be the latest one. But I also don't know how Maven works, so I may have just been doing it wrong. :-)

**Comment by Scottmitch** [comment]
@davidben - Ok thanks for clarifying. We have a PR against Netty that hasn't been pulled in yet to switch the package names https://github.com/netty/netty/pull/5766.

I just built this PR an ran against this https://github.com/netty/netty/pull/5766 and all is well.

@normanmaurer - we should configure the CI to build the `master` branch (and move away from 1.1.33)

**Comment by normanmaurer** [comment]
I would like to only merge this into master... Let me rebase it against master and merge soon.

**Comment by Scottmitch** [comment]
> only merge this into master

+1.

> Let me rebase it against master

This PR is opened against master ... did something get merged into master recently to cause a conflict?

**Comment by normanmaurer** [comment]
Yep... there were a few commits missing. I cherry-picked these earlier today

**Comment by davidben** [comment]
Rebased.

**Comment by normanmaurer** [comment]
Thanks a lot!

**Comment by Scottmitch** [comment]
lgtm

@normanmaurer - I'll let you merge in case you planned on doing any followup.

**Comment by davidben** [comment]
Anything else left to be done here?

**Comment by normanmaurer** [comment]
@danbev nope... I will pick this up this week.

**Comment by normanmaurer** [comment]
@davidben thanks a lot for your patience. Merged into master FTW :)

**Comment by Scottmitch** [comment]
thanks @davidben !

**Pull request closed without merging**
