### PR TITLE
Use OPENSSL_malloc and OPENSSL_free

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We used malloc and free directly in a few places while in others OPENSSL_malloc / OPENSSL_free are used.

Modifications:

Replace malloc calls with OPENSSL_malloc
Replace free calls with OPENSSL_free

Result:

More consistent way of allocating and freeing memory.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@Scottmitch want to have a look as well ?

**Comment by normanmaurer** [comment]
Cherry-picked into master (abded87)

**Comment by normanmaurer** [comment]
I just wanted to make it consistent and as you stated it not hurts

**Comment by Scottmitch** [comment]
It is a bit misleading on first glance. Typically `OPENSSL_malloc` and `OPENSSL_free` are used when it is expected that OpenSSL will eventually free the memory, but this is not the case here.

**Pull request closed without merging**
