### PR TITLE
Update openssl to 1.0.2i

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

New version of openssl was released

Modifications:

Update version.

Result:

Use up to date version.

### CODE REVIEW

**Comment by nmittler** [comment]
LGTM

**Comment by normanmaurer** [comment]
@nmittler this was an easy one to review =P

**Comment by nmittler** [comment]
+1 much appreciated :P

**Comment by normanmaurer** [comment]
Cherry-picked as 2f7d38fa68b007c3f761d226e09cc6ec0efc9b97

**Pull request closed without merging**
