### PR TITLE
Enable static module linking for Java 1.8

### PR DESCRIPTION
**Pull request by carl-mastrangelo**
Motivation:
Statically compiling JNI libraries causes problems when there are multiple in
use.  JDK 1.8 allows a work around by supporting a suffix for load calls.
The need for this is rare, but it's easy enough to fix it.

Modifications:
Chain the JNI_OnLoad and JNI_OnUnload calls to their suffixed counterparts.
Also allow a preprocessor define to set the JNI_VERSION, which is required
for static linking in 1.8.

Result:
The preexisting behavior stays put, but it is now possible for projects to
selectively change how they build TCN.

Fixes: #146

### CODE REVIEW

**Comment by Scottmitch** [comment]
@normanmaurer @carl-mastrangelo - any idea on the build failure? I just build on my local box with jdk8 and jdk7 and all seems ok.

https://garage.netty.io/teamcity/viewLog.html?buildId=8970&buildTypeId=pulls_netty_tcnative&guest=1
> [io.netty:netty-tcnative-boringssl-static] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-boringssl) on project netty-tcnative-boringssl-static: An Ant BuildException has occured: exec returned: 1
around Ant part ...<exec dir="/var/lib/teamcity-agent/work/dd2ea5c9a46891e0/boringssl-static/target/boringssl-chromium-stable/build" resolveexecutable="true" executable="ninja" failonerror="true"/>... @ 28:181 in /var/lib/teamcity-agent/work/dd2ea5c9a46891e0/boringssl-static/target/antrun/build-main.xml

**Comment by carl-mastrangelo** [comment]
Something with assembly:

```
[18:21:16][io.netty:netty-tcnative-boringssl-static]      [exec] FAILED: /opt/gcc/bin/gcc  -DBORINGSSL_IMPLEMENTATION -I../crypto/../include -I../crypto/chacha/../../include -Wa,--noexecstack -Wa,--noexecstack -O3 -DNDEBUG -fPIC -MMD -MT crypto/chacha/CMakeFiles/chacha.dir/chacha-x86_64.S.o -MF crypto/chacha/CMakeFiles/chacha.dir/chacha-x86_64.S.o.d -o crypto/chacha/CMakeFiles/chacha.dir/chacha-x86_64.S.o -c crypto/chacha/chacha-x86_64.S
[18:21:16][io.netty:netty-tcnative-boringssl-static]      [exec] crypto/chacha/chacha-x86_64.S: Assembler messages:
[18:21:16][io.netty:netty-tcnative-boringssl-static]      [exec] crypto/chacha/chacha-x86_64.S:1002: Error: no such instruction: `vbroadcasti128 .Lsigma(%rip),%ymm11'
[18:21:16][io.netty:netty-tcnative-boringssl-static]      [exec] crypto/chacha/chacha-x86_64.S:1003: Error: no such instruction: `vbroadcasti128 (%rcx),%ymm3'
[18:21:16][io.netty:netty-tcnative-boringssl-static]      [exec] crypto/chacha/chacha-x86_64.S:1004: Error: no such instruction: `vbroadcasti128 16(%rcx),%ymm15'
[18:21:16][io.netty:netty-tcnative-boringssl-static]      [exec] crypto/chacha/chacha-x86_64.S:1005: Error: no such instruction: `vbroadcasti128 (%r8),%ymm7'
[18:21:16][io.netty:netty-tcnative-boringssl-static]      [exec] crypto/chacha/chacha-x86_64.S:1011: Error: suffix or operands invalid for `vpshufd'
```

**Comment by carl-mastrangelo** [comment]
Any way to retrigger the tests?

**Comment by Scottmitch** [comment]
@carl-mastrangelo - Done. I re-ran tests the other day and got the same failure though.

https://garage.netty.io/teamcity/viewType.html?buildTypeId=pulls_netty_tcnative&branch_pulls=149&tab=buildTypeStatusDiv

**Comment by carl-mastrangelo** [comment]
@Scottmitch Alas, that page asks me to login, which I don't have credentials for.

**Comment by Scottmitch** [comment]
@carl-mastrangelo - Sorry about that. The summary is there are 4 builds on this commit with the same failure (chacha is trying to use assembly instructions that aren't supported on the build server). I'm guessing there is some build flag that isn't set as expected?

**Comment by normanmaurer** [comment]
@carl-mastrangelo @Scottmitch I will need to upgrade gcc version for this to work I think. We are using 4.8 and I think we need 4.9. Will check tomorrow

**Comment by normanmaurer** [comment]
Seems like a new gcc version does not help.. Suspect it is gnu assembler version. Trying to compile new binutils version atm.. Staying tuned. @carl-mastrangelo @nmittler is there some "requirement" page for boringssl ?

**Comment by nmittler** [comment]
@normanmaurer The only one I know of is https://boringssl.googlesource.com/boringssl/+/HEAD/BUILDING.md

@davidben may have more info

**Comment by davidben** [comment]
I appear to be building with 4.8 without trouble. Can you build OpenSSL from git? That assembly file's from upstream. (Also, I'm confused why the C compiler and Java version are correlated.)

**Comment by normanmaurer** [comment]
@davidben let me check...

**Comment by normanmaurer** [comment]
@davidben @nmittler @carl-mastrangelo actually it compiles now.. Just used latest binutils and all is good ... Maybe would be good to document it somehow :)

**Comment by normanmaurer** [comment]
Cherry-picked into 1.1.33 as cf8d01b1ec6872c5ae2530cc40cecdd2caa37ff8.

@carl-mastrangelo thanks!

**Comment by normanmaurer** [comment]
On centos 6.7 it was:

```
GNU assembler version 2.20.51.0.2 (x86_64-redhat-linux) using BFD version version 2.20.51.0.2-5.43.el6 20100205
```

**Comment by normanmaurer** [comment]
@davidben see above

**Comment by davidben** [comment]
Ah. (I've now documented the requirement in https://boringssl.googlesource.com/boringssl/+/f6a74c61f7455885a514e577d69670f924b6cf6f%5E%21/ )

**Comment by normanmaurer** [comment]
@davidben thanks!

**Pull request closed without merging**
