### PR TITLE
Correctly process JNI escape sequence _1 (#419)

### PR DESCRIPTION
**Pull request by kennknowles**
Current logic incorrectly interprets e.g. `a_b_1c` as `a/b/1c` instead of the correct `a/b_c`. After this patch, the `_1` is processed as an underscore.

### CODE REVIEW

**Comment by kennknowles** [comment]
@normanmaurer this is more of a demonstration of what the logic might be... I'm quite sure I am not utilizing the libs I ought to, and I'm not sure where a test for this would fit in. If you point me to the place to add a test, I'll give it a try.

**Comment by normanmaurer** [comment]
@kennknowles we have some tests related to shading netty. So maybe you can add these there ?

https://github.com/netty/netty/tree/4.1/testsuite-shading

**Comment by normanmaurer** [comment]
@kennknowles ping

**Comment by kennknowles** [comment]
Still alive, just got busy!

**Comment by hyperxpro** [comment]
Just checking if you got any update @kennknowles ?

**Comment by trustin** [comment]
Sorry that it took so long. It should be fixed via the following PRs:

- https://github.com/netty/netty-jni-util/pull/13
- https://github.com/netty/netty/pull/12358
- https://github.com/netty/netty-tcnative/pull/726

**Pull request closed without merging**
