### PR TITLE
pom.xml:adding option for aarch64 to build

### PR DESCRIPTION
**Pull request by ossdev07**
adding option linux-aarch_64 to create jar in aarch64

Signed-off-by: ossdev <ossdev@puresoftware.com>

### CODE REVIEW

**Comment by ossdev07** [comment]
@normanmaurer can you please have a look on this change for aarch64 platform

**Comment by normanmaurer** [comment]
@ossdev07 I wonder why this is needed... are you running `mvn release:*` by yourself ?

**Comment by ossdev07** [comment]
@normanmaurer to build netty-transport-native-epol on aarch64l i need to build netty-tcnative  for aarch64 platform that's it is there
will you please check it ..

**Comment by normanmaurer** [comment]
@ossdev07 I am still confused why you need this change tho.. The restrict rule should only apply during `mvn release:*` so you should already be able to just build it via `mvn clean package` without the change. Can you elaborate ?

**Comment by ossdev07** [comment]
@normanmaurer can we use maven plugins in transport-native-epoll to generate aarch64 stuff in x64 platform in same jar as used in netty-tcnative/openssl-dynamic (build-native-lib) . in my opinion this solution will solve the problem of releasing for different architecture.. if it suits you i can raise pull  request to check the changes.

**Comment by johnou** [comment]
@ossdev07 ptal https://github.com/netty/netty-tcnative/pull/517

**Comment by normanmaurer** [comment]
Lets close this in favour of https://github.com/netty/netty-tcnative/pull/517

**Pull request closed without merging**
