### PR TITLE
Skip unknown signature algorithms when when collect signatures in SSL…

### PR DESCRIPTION
**Pull request by normanmaurer**
….getSigAlgs(...)

Motivation:

We did not correctly account for unknown signature algorithms when using BoringSSL but just returned NULL if we accountered one (and discard all the known salgorithms). We should just ignore the unknown and return the others.

Modifications:

Skip unkown signature algorithms and correctly return the known.

Result:

Fixes https://github.com/netty/netty-tcnative/issues/448.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@kwart this should fix your problem. Can you verify ?

**Comment by kwart** [comment]
I'm going to check it with your branch.

**Comment by kwart** [comment]
The `EchoServer` reproducer works correctly with the fix. Let me check it also in the Hazelcast Enterprise testsuite where we originally hit the issue.

**Comment by kwart** [comment]
The Hazelcast tests passed too :+1:
Thanks for the fix. Looking forward for the new release.

**Comment by normanmaurer** [comment]
This is the unit test for it https://github.com/netty/netty/pull/8965

**Comment by normanmaurer** [comment]
@kwart thanks for testing the fix :)

**Pull request merged**
