### PR TITLE
[WIP] Add a gradle configuration that builds tcnative linux versions within…

### PR DESCRIPTION
**Pull request by anuraaga**
… docker while also executing the host build.

Motivation: Currently tcnative does not run on Alpine linux due to libc incompatibility. By having more flexible building, taking advantage of docker, it should be possible to provide official binaries without much extra work during release.

See also #111, #152 

I went ahead and hacked this setup together to allow more flexibility in tcnative builds. Without more knowledge of the release process, I can't say this does exactly what's needed but will be happy to continue to update until it can be used for releasing. FWIW, ~/.m2/repository gets populated with the right jars so it should be mostly there :)

This PR does not change the tcnative build to gradle - that would be a much more invasive process. It uses gradle to take advantage of its flexibility in task execution - looking at examples of maven-docker-plugin made it look like it'd result in an unreadable pom.xml.

With this setup, it would be possible to build all of OSX (or windows which also has docker) and linux versions on the same machine. Care has been taken to allow the versions to be built in parallel using gradle's incubating parallel projects feature. On my macbook pro, all the builds end in about 20min.

```
# This builds three versions of tcnative in parallel
./gradlew buildAll
```

Another feature of this gradle script is it automatically downloads and runs maven. So for building linux binaries, the requirements are literally just Java and Docker.

Main questions I currently have are
1) The top-level pom restricts releasing to RHEL 6.8. How do the other versions get released?
2) RHEL 6.8 will produce openssl-dynamic with the fedora classifier since it's fedora-like. What distribution is used to build the non-fedora-like version? It'd be easy to add it here too :)

### CODE REVIEW

**Comment by anuraaga** [comment]
@normanmaurer Hope this looks useful, PTAL whenever you get a chance :)
/cc @trustin @pires

**Comment by anuraaga** [comment]
@normanmaurer Hello - just checking in, does this generally seem reasonable? The hope is to make releasing easier for the maintainers by reducing the needed VMs :)

**Comment by normanmaurer** [comment]
@anuraaga sorry I had no time yet and just returned back from the US. I will have a look this week.

**Comment by anuraaga** [comment]
@normanmaurer Hey - long time no check-in. Is there any future for this or official alpine linux support in tcnative? If not, I should just go ahead and close it I think.

**Pull request closed without merging**
