### PR TITLE
Port Apache Tomcat Native changes

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

Apache Tomcat Native did some changes which are relevant to us as well.

Modifications:

Port the following changes:
https://github.com/apache/tomcat-native/commit/d2b1478c2a2d5f0848e3acafec61b8858ce13381
https://github.com/apache/tomcat-native/commit/06ed114da4800889ed69531e96227358d9d1ba02
https://github.com/apache/tomcat-native/commit/5c167e1cb9bd757d60280dbcdb48d2298117a593
https://github.com/apache/tomcat-native/commit/224bf34c68c03dc12616436e09c7360bd69b55b7

Result:

Be able to use openssl master

### CODE REVIEW

**Comment by normanmaurer** [comment]
@nmittler @Scottmitch FYI

**Comment by Scottmitch** [comment]
lgtm ... defect or feature?

**Comment by normanmaurer** [comment]
I guess both ;)

**Comment by normanmaurer** [comment]
Cherry-picked into 1.1.33 (444598b) and next (c4c87de)

**Pull request closed without merging**
