### PR TITLE
Fix possible segfault when using LibreSSL and not SSL2

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We used a non API to get the cipher during the certificate verification which worked in OpenSSL, BoringSSL and older versions of LibreSSL. In newer versions of LibreSSL this leads to a segfault.

Modifications:

Use public api to get the cipher.

Result:

No more segfault when using newer versions of LibreSSL.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@nmittler PTAL 

@blucas @fbettag I think you reported this to me before as well.

**Comment by fbettag** [comment]
Yes i did like a year ago :D but i'll recheck

**Comment by normanmaurer** [comment]
@fbettag yeah... at this point I thought it would be a libressl bug but I was wrong :(

**Comment by nmittler** [comment]
@normanmaurer LGTM .... ship it!

**Comment by normanmaurer** [comment]
Cherry-picked into 1.1.33 as 5a4b3f636b40cf136f63c448e7ddf5f09935bf91

**Pull request closed without merging**
