### PR TITLE
[#104] Remove unused code

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

We only use a sub-set of the original tcnative code that we forked. We should remove everything we not care about.

Modification:

Remove all stuff that we not need and want to maintain.

Result:

Less code to maintain.

### CODE REVIEW

**Comment by normanmaurer** [comment]
@Scottmitch @trustin @nmittler PTAL... After this is merged I will take a look what it will take to remove apr dependency and if make sense.

**Comment by nmittler** [comment]
@normanmaurer Looks like it's literally all deletes.  Assuming it works, ship it!

+1 for less code!! :)

**Comment by Scottmitch** [comment]
Soo much red ... ship it!

**Comment by trustin** [comment]
Awesome :-)

**Comment by normanmaurer** [comment]
seems like I fucked up somehow... this not works :( Let me close and re-open once figured out.

**Pull request closed without merging**
